services:

  redis:
    image: redis:alpine
    container_name: redis-db
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - services


  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - services

  menu:
    container_name: menu
    build:
      context: ./menu
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./menu/.env
    depends_on:
      - db
    networks:
      - services

  nginx:
    image: nginx:latest
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/
    depends_on:
      - menu
    networks:
      - services

networks:
  services:
    driver: bridge
