events {}

http {

    upstream menu_service {
        server menu:4000;
    }

    upstream order_service {
        server order:4001;
    }

    upstream payment_service {
        server payment:4002;
    }

    upstream kitchen_service {
        server kitchen:4003;
    }

    upstream notification_service {
        server notification:4004;
    }

    server {
        listen 80;

        location /api/v1/menu/ {
            proxy_pass http://menu_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/order/ {
            proxy_pass http://order_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/payment/ {
            proxy_pass http://payment_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/kitchen/ {
            proxy_pass http://kitchen_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/notification/ {
            proxy_pass http://notification_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
    }
}