events {}

http {
    upstream menu {
        server menu-api:4000;
    }

    upstream order {
        server order-api:4000;
    }

    server {
        server_name app.com;
         
        location /menu {
            proxy_pass http://menu;
        }

        location /order {
            proxy_pass http://order;
        }
    }
}
