events {}

http {

    upstream menu {
        server menu:4000;
    }

    upstream order {
        server order:4001;
    }

    upstream payment {
        server payment:4002;
    }

    upstream kitchen {
        server kitchen:4003;
    }

    upstream notification {
        server notification:4004;
    }

    server {
        listen 80;
        server_name app.com;

        location /api/v1/menu/ {
            proxy_pass http://menu;
        }

        location /api/v1/orders/ {
            proxy_pass http://order;
        }

        location /api/v1/payments/ {
            proxy_pass http://payment;
        }

        location /api/v1/tickets/ {
            proxy_pass http://kitchen;
        }

        location /api/v1/notifications/ {
            proxy_pass http://notification;
        }
    }
}
